language: java

before_script:
  - export BRANCH=$(if [ "$TRAVIS_PULL_REQUEST" == "false" ]; then echo $TRAVIS_BRANCH; else echo $TRAVIS_PULL_REQUEST_BRANCH; fi)
  - echo "TRAVIS_BRANCH=$TRAVIS_BRANCH, PR=$PR, BRANCH=$BRANCH"
  - ./gradlew compileTestKotlinJs

after_success:
  - test $TRAVIS_BRANCH != "master" && ./gradlew bintrayUpload
  - test $TRAVIS_BRANCH == "master" && ./gradlew release -Prelease.useAutomaticVersion=true
